version: '3'

services:
  wiremock:
    image: wiremock/wiremock
    ports:
      - '8080:8080'
    command: --global-response-templating --extensions com.github.asrakuten.ExampleTransformer
    volumes:
      - .:/home/wiremock
      - ./extensions:/var/wiremock/extensions
